server:
  port: 8080
  servlet:
    context-path: /clw-ser

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:33060/book
        username: root
        password: etoak
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.clw.clw_ser.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: etoak
    supportMethodsArguments: true
    params: count=countSql